'use strict';
/**
 * Rudy OS brand mark: the pixel R on the ink tile, burgundy offset shadow.
 *
 * THE GEOMETRY IS THE BRAND MASTER. Same rects as docs/rudy-os-mark.svg and
 * the exported files in the brand kit (rudy-mark-tile): everything is an
 * axis-aligned rectangle on a 12px grid of the 456px master, so every output
 * here is pixel-exact at any size. No fonts, no gradients, no filters.
 *
 * Two compositions from one geometry:
 *   tile  the full lockup: margin, burgundy offset shadow, ink tile, lemon R.
 *         Used where the mark floats on a page or a dock.
 *   full  the ink tile edge to edge with the lemon R, opaque.
 *         Used where the platform crops or tiles the icon itself
 *         (favicons, .ico, apple-touch).
 *
 * Writes, from one source:
 *   docs/logo.svg             source of truth (tile, vector)
 *   docs/logo.png        512  site header (dark), README
 *   docs/logo-light.png  512  site header (light)
 *   docs/favicon-32.png   32  native-size favicon
 *   docs/apple-touch-icon.png 180
 *   build/icon.svg            design source for the app icon
 *   build/icon.png      1024  Linux, and the electron-builder base
 *   build/icon.ico            Windows, full bleed, 16..256
 *   build/icon.icns           macOS, tile composition, 16..1024
 *
 *   node tools/make-logo.cjs
 */

const fs = require('node:fs');
const path = require('node:path');
const zlib = require('node:zlib');
const { execFileSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');

// ── geometry, in 12px units of the 456px master ───────────────────────────
const INK = [17, 17, 17];        // #111111  the tile
const LEMON = [244, 211, 94];    // #F4D35E  the R
const BURG = [110, 20, 35];      // #6E1423  the offset shadow

const TILE_U = 28;               // tile edge
const CANVAS_U = 38;             // tile + margin + shadow overhang
const MARGIN_U = 4;              // tile origin inside the canvas
const SHADOW_U = 2;              // shadow offset (down and right)

// The R, relative to the tile origin. Stem, bar, bowl, bar, leg, foot.
// The foot lands exactly on the tile's bottom edge (24 + 4 = 28).
const R_RECTS = [
  [7, 9, 4, 16],
  [11, 9, 8, 4],
  [19, 13, 4, 4],
  [11, 17, 8, 4],
  [15, 21, 4, 4],
  [19, 24, 4, 4],
];

/** Rect list for one composition, in canvas units. */
function rects(comp) {
  if (comp === 'full') {
    return {
      canvas: TILE_U,
      list: [
        { x: 0, y: 0, w: TILE_U, h: TILE_U, c: INK },
        ...R_RECTS.map(([x, y, w, h]) => ({ x, y, w, h, c: LEMON })),
      ],
    };
  }
  const m = MARGIN_U, s = SHADOW_U;
  return {
    canvas: CANVAS_U,
    list: [
      { x: m + s, y: m + s, w: TILE_U, h: TILE_U, c: BURG },
      { x: m, y: m, w: TILE_U, h: TILE_U, c: INK },
      ...R_RECTS.map(([x, y, w, h]) => ({ x: x + m, y: y + m, w, h, c: LEMON })),
    ],
  };
}

// ── SVG ───────────────────────────────────────────────────────────────────
const hex = (c) => '#' + c.map((v) => v.toString(16).padStart(2, '0')).join('').toUpperCase();

function buildSvg(N, comp) {
  const { canvas, list } = rects(comp);
  const u = N / canvas;
  const body = list
    .map((r) => `  <rect x="${r.x * u}" y="${r.y * u}" width="${r.w * u}" height="${r.h * u}" fill="${hex(r.c)}"/>`)
    .join('\n');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${N}" height="${N}" viewBox="0 0 ${N} ${N}" shape-rendering="crispEdges" role="img" aria-label="Rudy OS">
  <!-- Rudy OS brand mark. Generated by tools/make-logo.cjs; edit that, not this.
       Same geometry as docs/rudy-os-mark.svg, the brand master. -->
  <title>Rudy OS</title>
${body}
</svg>
`;
}

// ── PNG ───────────────────────────────────────────────────────────────────
const CRC = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return (buf) => {
    let c = -1;
    for (let i = 0; i < buf.length; i++) c = t[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
    return (c ^ -1) >>> 0;
  };
})();

function chunk(type, data) {
  const len = Buffer.alloc(4); len.writeUInt32BE(data.length);
  const td = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4); crc.writeUInt32BE(CRC(td));
  return Buffer.concat([len, td, crc]);
}

function encodePng(N, rgba) {
  const stride = N * 4 + 1;
  const raw = Buffer.alloc(N * stride);
  for (let y = 0; y < N; y++) {
    raw[y * stride] = 0;
    rgba.copy(raw, y * stride + 1, y * N * 4, (y + 1) * N * 4);
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(N, 0); ihdr.writeUInt32BE(N, 4);
  ihdr[8] = 8; ihdr[9] = 6;
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', zlib.deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0))
  ]);
}

/**
 * Rasterise by painting rects with per-edge rounding: every edge snaps to the
 * nearest device pixel independently, so edges stay razor sharp at any size
 * and adjacent rects never leave a seam. No anti-aliasing anywhere, which is
 * the point: this is pixel art.
 */
function rasterise(N, comp) {
  const { canvas, list } = rects(comp);
  const u = N / canvas;
  const out = Buffer.alloc(N * N * 4);
  for (const r of list) {
    const x0 = Math.round(r.x * u), x1 = Math.round((r.x + r.w) * u);
    const y0 = Math.round(r.y * u), y1 = Math.round((r.y + r.h) * u);
    for (let y = y0; y < y1; y++) {
      for (let x = x0; x < x1; x++) {
        const i = (y * N + x) * 4;
        out[i] = r.c[0]; out[i + 1] = r.c[1]; out[i + 2] = r.c[2]; out[i + 3] = 255;
      }
    }
  }
  return encodePng(N, out);
}

// ── ICO ───────────────────────────────────────────────────────────────────
function buildIco(pngs) {
  const dir = Buffer.alloc(6);
  dir.writeUInt16LE(0, 0); dir.writeUInt16LE(1, 2); dir.writeUInt16LE(pngs.length, 4);
  let offset = 6 + pngs.length * 16;
  const entries = [], bodies = [];
  for (const { size, data } of pngs) {
    const e = Buffer.alloc(16);
    e[0] = size >= 256 ? 0 : size;
    e[1] = size >= 256 ? 0 : size;
    e.writeUInt16LE(1, 4); e.writeUInt16LE(32, 6);
    e.writeUInt32LE(data.length, 8); e.writeUInt32LE(offset, 12);
    entries.push(e); bodies.push(data);
    offset += data.length;
  }
  return Buffer.concat([dir, ...entries, ...bodies]);
}

// ── run ───────────────────────────────────────────────────────────────────
const D = (p) => path.join(ROOT, p);
const wrote = [];
const write = (rel, buf) => {
  fs.writeFileSync(D(rel), buf);
  wrote.push(`${rel.padEnd(28)} ${(buf.length / 1024).toFixed(1)} KB`);
};

write('docs/logo.svg', Buffer.from(buildSvg(1024, 'tile')));
write('docs/logo.png', rasterise(512, 'tile'));
write('docs/logo-light.png', rasterise(512, 'tile'));
write('docs/favicon-32.png', rasterise(32, 'full'));
write('docs/apple-touch-icon.png', rasterise(180, 'full'));

write('build/icon.svg', Buffer.from(buildSvg(1024, 'tile')));
write('build/icon.png', rasterise(1024, 'tile'));
write('build/icon.ico', buildIco([16, 32, 48, 64, 128, 256].map((size) => ({
  size, data: rasterise(size, 'full')
}))));

const setDir = D('build/icon.iconset');
fs.rmSync(setDir, { recursive: true, force: true });
fs.mkdirSync(setDir, { recursive: true });
for (const [name, size] of [
  ['icon_16x16', 16], ['icon_16x16@2x', 32], ['icon_32x32', 32], ['icon_32x32@2x', 64],
  ['icon_128x128', 128], ['icon_128x128@2x', 256], ['icon_256x256', 256],
  ['icon_256x256@2x', 512], ['icon_512x512', 512], ['icon_512x512@2x', 1024]
]) {
  fs.writeFileSync(path.join(setDir, `${name}.png`), rasterise(size, 'tile'));
}
execFileSync('iconutil', ['-c', 'icns', setDir, '-o', D('build/icon.icns')]);
fs.rmSync(setDir, { recursive: true, force: true });
wrote.push(`build/icon.icns              ${(fs.statSync(D('build/icon.icns')).size / 1024).toFixed(1)} KB`);

console.log(wrote.join('\n'));
